apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-deployment
  labels:
    app: sprintapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sprintapp
  template:
    metadata:
      labels:
        app: sprintapp
    spec:
      containers:
      - name: rmkv-track
        image: dinesh14coder/rmkv:angular16
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-cred

