apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-deployment
  labels:
    app: sprint-track-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sprint-track-app
  template:
    metadata:
      labels:
        app: sprint-track-app
    spec:
      containers:
      - name: Sprint-track
        image: dinesh14coder/rmkv:angular4
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-cred

