apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-deployment
  labels:
    app: trackapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trackapp
  template:
    metadata:
      labels:
        app: trackapp
    spec:
      containers:
      - name: rmkv-track
        image: dinesh14coder/rmkv:dotnet10
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-cred
